### PR TITLE
fix driver control arm retracting

### LINKED ISSUE #20: Arm retracting without command
@lcdnbl The arm will retract completely autonomously, unsure why. This needs to be resolved before meet 12/30/23. Greatly detrimental to driver 2 during gameplay.

### PR DESCRIPTION
**Pull request by lcdnbl**
Fixes #20

### CODE REVIEW

File: AutoCommon.java [hunk 1]
```diff
@@ -181,7 +184,8 @@ public void dropBottomPixel() {
    * COMMON DRIVE FUNCTION:
    *   Used to simplify autonomous programming with simple & readable cmds
    ************************************************************************/
-  public void drive(double fwd_bck, double right_left, double cw_ccw, double power) {
+  public void drive(double fwd_bck, double right_left, double cw_ccw, double power)
```
Comment (lcdnbl) [inline AutoCommon.java]: The opening bracket for the drive function was lost in the edit

Comment (lcdnbl) [reply AutoCommon.java]: fixed with ae155211c733b239cfa4fae291177697ef5ea9b5
